fix: workmanager update broke ios build
Error: The plugin "workmanager_apple" requires a higher minimum iOS deployment version than your application is targeting.
To build, increase your application's deployment target to at least 13.0 as described at https://flutter.dev/to/ios-deploy